### ISSUE TITLE
Readme unclear

### ISSUE THREAD

**Issue by Radiergummi** [Kocal/jsdoc-vuejs#11]
It's two things that confuse me a little:

a) What does the *WARNING: Actually, it's only working with the default JSDoc template.* refer to?
b) Why is the `@vue` necessary? We're inside of a `.vue` file, so that should be pretty clear already?

**Comment by Kocal** [comment]
Hey!

### Question a)

It's due to my lack of knowledge of JSDoc or JSDoc's own limitations. 

I wanted to display data/computed/props/methods/hooks of a Vue component, like JSDoc do for class methods, properties, etc ...

Since I wasn't able to do that, I had to use a [dirty trick](https://github.com/Kocal/jsdoc-vuejs/blob/89ca2f11647724cfdfab94b989f2635451afb8c2/index.js#L28) for writing plain HTML. And this plain HTML is specific to the default JSDoc template.

### Question b)

It's related to my dirty trick with plain HTML. 

When JSDoc is creating a doclet, it triggers a [`newDoclet`](http://usejsdoc.org/about-plugins.html#event-newdoclet) event. This event takes one parameter which is the doclet currently processed.

This parameter does not contain anything that could help me identify if we are in a Vue file or not. So I had to use [doclet's scope](https://github.com/Kocal/jsdoc-vuejs/blob/89ca2f11647724cfdfab94b989f2635451afb8c2/index.js#L24) which has been previously updated by the [`@vue` tag](lib/vueTag.js).

**Comment by Radiergummi** [comment]
Okay, thank you for the quick answer. Thats helpful! 😊
