### ISSUE TITLE
@method annotations ?

### ISSUE THREAD

**Issue by bpod** [Kocal/jsdoc-vuejs#118]
This is more of a question. Does this support marking up methods? I've tried a couple things that do not seem to be working.

**Comment by bpod** [comment]
NVM... figured it out..

**Comment by GerkinDev** [comment]
Hey there!
It would be nice if you explain your solution, because it's still not working for me..

**Comment by Kocal** [comment]
There is no `@vue-method` annotations because in fact (after some tricks), it's JSDoc itself that parse and render them in the documentation.

You can take a look to this [example](https://github.com/Kocal/jsdoc-vuejs/blob/master/example/src/better-components/BetterCounter.vue) and to its [integration test](https://github.com/Kocal/jsdoc-vuejs/blob/master/cypress/integration/templates/default.spec.js#L180)
